### PR TITLE
Added support for hound

### PR DESCRIPTION
**Pull request by praveendhawan**
added support for hound

### CODE REVIEW

**Comment by praveendhawan** [comment]
@tansaku, @mattwr18 we might need to follow these steps for passing build on circle ci - https://dev.to/vinhnglx/integration-testing-phoenix-application-with-circle-ci-20-50md

**Comment by tansaku** [comment]
great work on this @praveendhawan and @mattwr18 

probably some changes needed to CI - currently failing with:

```
  1) test when two users choose 'pair' from the homepage, they are added to a Jitsi (Paironauts.AcceptanceTest)
     test/browser/acceptance_test.exs:31
     ** (exit) exited in: GenServer.call(Hound.SessionServer, {:change_session, #PID<0.467.0>, :default, []}, 60000)
         ** (EXIT) an exception was raised:
             ** (RuntimeError) could not create a new session: econnrefused, check webdriver is running
                 (hound) lib/hound/session_server.ex:101: Hound.SessionServer.create_session/2
                 (hound) lib/hound/session_server.ex:78: Hound.SessionServer.handle_call/3
                 (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
                 (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
                 (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by tansaku** [comment]
btw, @praveendhawan, if you put the issue number at the start of the branch (e.g. 22_hound_setup) it makes it super-easy to tab complete off just the issue number - are you a big fan of putting it at the tail end of the branch name?

**Comment by praveendhawan** [comment]
@tansaku Yeah you will need to install phantomjs on your local and start it as a service using `phantomjs --wd` which will start phatomjs server.

About the branch naming, not a big fan, its just kind of became a habit to include the issue number at the tail.

**Comment by praveendhawan** [comment]
Probably Out of date code. So closing this one.

**Pull request closed without merging**
